# torch package

In [1]:
import torch

## Random sampling

In [ ]:
# TODO

## Math operations

### Pointwise Ops

#### torch.abs(input, out=None) -> Tensor

In [2]:
# Computes the element-wise absolute value of the given input tensor.
# torch.abs(input, out=None) -> Tensor
print(torch.abs(torch.tensor([-1, -2, 3])))

tensor([1, 2, 3])


In [9]:
a = torch.tensor([1, 2], dtype=torch.int)
print(a.dtype)

print(torch.add(a, 20))

torch.int32
tensor([21, 22], dtype=torch.int32)


In [10]:
# Returns a new tensor with the ceil of the elements of input, the smallest integer greater than or equal to each 
# element
a = torch.randn(4)
print(a)
print(torch.ceil(a))

tensor([-0.0385,  0.9521,  0.0685,  0.0661])
tensor([-0.,  1.,  1.,  1.])
